### ISSUE TITLE
MenuItem options

### ISSUE THREAD

**Issue by criticalmash** [criticalmash/assemble-navigation#7]
add an options variable to the `MenuItem()` constructor.

``` js
new MenuItem(view, options);
```

Options would be an object whose attributes would override any options set by the view. Use cases would be...
- Creation of non-view menu items
- ability to set different sets of options depending on the menu. If a page needs to appear in the submenu of the main menu and the root of the footer menu, we can attach custom option sets to each menu when declared in the front matter, like so...

``` yaml
title: My Page
menus:
  - main
  - menu-name: footer
    menuPath: mypage
    menu-title: Mine
```
